### ISSUE TITLE
RiakCS ACL 

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-riakcs#1]
Original reporter: @panteo at fog/fog#2985
### Disclaimer

This is my first public contribute to the community and I'm not native english, so, please, help me if I'm doing something wrong. Thanks. ;-)
### Problem

I have a problem with `put_bucket_acl` and I can't figure if it's a bug or it's related to my config.

After PUT, grantee ID and DisplayName are set to nil but Permission is correctly updated. Removing the new lines and with spaces from body solved the problem.

[Here](https://github.com/panteo/fog/commit/663f922a65814f37ef9e495aa9aae6bba10f9bf9) it is my patch.
### About my config (One RiakCS server)

OS: Ubuntu 14.04 LTS x86_64
Kernel: 3.13.0-27-generic
RiakCS: 1.4.5-1
Riak: 1.4.9-1
Nginx: 1.4.6-1ubuntu3
Protocol: HTTPS with valid wildcard certificate

**Comment by plribeiro3000** [comment]
@geemus Someone to take care of this? Otherwise i will see what i can do about it.

@panteo Can you create a PR against this repo with your patch so we can work on top of it?

**Comment by panteo** [comment]
I hope I have done everything right.

**Comment by plribeiro3000** [comment]
@panteo Your patch should be against this repo `fog-riakcs` and not `fog`.

Your PR can't be merged because i moved all the files to this repo. Can you reopen it again please?

**Comment by panteo** [comment]
Sorry, I can't. In the new repo there is no trace of the code I've patched, or I could not find it. Maybe the bug has already been fixed.

**Comment by geemus** [comment]
Could be possible. Just let us know if you need help, sorry for the confusion.

**Comment by plribeiro3000** [comment]
Hmmm. I think its because your patch changes `aws`, nor `riakcs`. This repo is for `riakcs` only.
Sorry for the confusion here. By looking at the title i was thinking this was related to `riakcs` code only.
